name: Build and push to ecr 

on:
  push:
    #pull_request:
      #branches: ['main','dev']
      branches: ['main']

jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Build Docker image
        run: |
          docker build -t 982081084137.dkr.ecr.us-east-1.amazonaws.com/dev:latest .

      - name: Trivy Docker image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 982081084137.dkr.ecr.us-east-1.amazonaws.com/dev:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
      
