name: Build and push to ecr 

on:
  push:
    #pull_request:
      #branches: ['main','dev']
      branches: ['main']
permissions:
  contents: read
  id-token: write
jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Build Docker image
        run: docker build -t 982081084137.dkr.ecr.us-east-1.amazonaws.com/dev:latest .

      - name: Trivy Docker image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 982081084137.dkr.ecr.us-east-1.amazonaws.com/dev:latest
          format: table
          exit-code: 0
          ignore-unfixed: true
          severity: CRITICAL,HIGH
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::982081084137:role/github-action-cicdrole
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to Amazon ecr
        run: 982081084137.dkr.ecr.us-east-1.amazonaws.com/dev:latest